version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.414.3-jdk11
    container_name: jenkins-master
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home
    