apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: martonowibowo/sample-app:pipeline-14 # Replace with your Docker image and tag
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
